### ISSUE TITLE
[Meta] Train simple nwp model

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix-archives/predict_pv_yield#106]
## Detailed Description
- [x] Train simple nwp model that uses CNN and one channel. 
- [x] save model to s3

other repos: 
- [x] s3 bucket: https://github.com/openclimatefix/nowcasting_infrastructure/issues/42
- [x] update forecast: https://github.com/openclimatefix/nowcasting_forecast/issues/41
- [x] add model id: https://github.com/openclimatefix/nowcasting_datamodel/issues/3

## Context
This will be good to be use as v1 of the nowcasting platform - https://docs.google.com/presentation/d/1qbi3Gpmfyc3PN1yZeUmlMbtV9Jl77HQ1sZ-L48gNFeY/edit#slide=id.g112471ef353_0_6

**Comment by peterdudfield** [comment]
Manage to train a model  - results are all ok. As good as needed

https://app.neptune.ai/o/OpenClimateFix/org/predict-pv-yield/e/PRED-951/all?path=validation%2Fplot%2F&attribute=epoch_1_4

**Comment by peterdudfield** [comment]
model is saved here - https://s3.console.aws.amazon.com/s3/buckets/nowcasting-ml-models-development?region=eu-west-1&tab=objects

**Comment by peterdudfield** [comment]
neptune run - https://app.neptune.ai/o/OpenClimateFix/org/predict-pv-yield/e/PRED-951/charts

**Comment by peterdudfield** [comment]
This has been deployed
